### ISSUE TITLE
home assistant hangs when trying to setup

### ISSUE THREAD

**Issue by ecto1a2003** [ryanwinter/hass-rainforest-emu-2#1]
![image](https://user-images.githubusercontent.com/16028846/162864810-061d2f0e-1be6-4e3d-b92a-183703414dd6.png)
wheel will spin and nothing will happen. have to bounce to get it back. nothing shows in logs

**Comment by ryanwinter** [comment]
Hi,

Did you get this working?

**Comment by ecto1a2003** [comment]
I did, had to fully remove my old module
