### ISSUE TITLE
Error on logs from sensor

### ISSUE THREAD

**Issue by TravHayes** [ryanwinter/hass-rainforest-emu-2#11]
After latest update getting error from the custom integration.
This error originated from a custom integration.

Logger: custom_components.rainforest_emu_2.emu2
Source: custom_components/rainforest_emu_2/emu2.py:142
Integration: Rainforest EMU-2 (documentation, issues)
First occurred: 9:06:33 PM (1 occurrences)
Last logged: 9:06:33 PM

Malformed XML: mand><DeviceMacId></DeviceMacId><MeterMacId></MeterMacId><TimeStamp>0x29fa2c39</TimeStamp><Demand>0x0003a1</Demand><Multiplier>0x00000001</Multi<InstantaneousDemand><DeviceMacId>0xd8d5b900000114a8</DeviceMacId><MeterMacId>0x001350020094b970</MeterMacId><TimeStamp>0x29fa2c48</TimeStamp><Demand>0x0003b1</Demand><Multiplier>0x00000001</Multiplier><Divisor>0x000003e8</Divisor><DigitsRight>0x03</DigitsRight><DigitsLeft>0x0f</DigitsLeft><SuppressLeadingZero>Y</SuppressLeadingZero></InstantaneousDemand>

**Comment by ryanwinter** [comment]
Fixed in https://github.com/ryanwinter/hass-rainforest-emu-2/pull/12
